name: Build Laravel Application

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, dom, fileinfo, mysql

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Install Composer dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Generate key
        run: php artisan key:generate

      - name: Install JS dependencies
        run: npm ci

      - name: Build assets
        run: npm run build

      - name: Create deployment package
        run: |
          mkdir -p deployment
          cp -R app bootstrap config database public resources routes storage vendor composer.json composer.lock .env deployment/
          # Copy built assets
          cp -R public/build deployment/public/ || true

      - name: Upload deployment artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ github.sha }}
          path: deployment/
          retention-days: 1 