name: Test Laravel Application

on:
  workflow_call:
    inputs:
      app_built:
        required: true
        type: boolean
        description: 'Whether the application has been built'

jobs:
  test:
    runs-on: ubuntu-latest
    if: ${{ inputs.app_built == true }}

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: testing
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, dom, fileinfo, mysql

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-${{ github.sha }}
          path: ./deployment

      - name: Restore build files
        run: |
          # Restore vendor directory
          cp -R deployment/vendor ./
          cp deployment/composer.json ./
          cp deployment/composer.lock ./
          
          # Restore Vite build files
          mkdir -p public/build
          cp -R deployment/public/build/* public/build/ || true
          
          # Restore other necessary directories
          cp -R deployment/bootstrap ./
          cp -R deployment/storage ./

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Set testing environment
        run: |
          echo "DB_CONNECTION=mysql" >> .env
          echo "DB_HOST=127.0.0.1" >> .env
          echo "DB_PORT=3306" >> .env
          echo "DB_DATABASE=testing" >> .env
          echo "DB_USERNAME=root" >> .env
          echo "DB_PASSWORD=password" >> .env

      - name: Generate application key
        run: php artisan key:generate

      - name: Run database migrations
        run: php artisan migrate --force

      - name: Run tests
        run: php artisan test --coverage